#! /bin/sh

set -e

echo "=> Stoping new fan controller script (screen)...\n"
screen -X -S fancontrol quit

echo "=> Uninstalling fan controller...\n"
sudo rm /usr/local/bin/fancontrol.py

sudo update-rc.d -f fancontrol.py remove

echo "Fan controller uninstalled."

